### ISSUE TITLE
CSS Error in Course Exploration Page

### ISSUE THREAD

**Issue by Steven-Jarmell** [pittcsc/pittcswiki#380]
When you go to 'https://pittcs.wiki/courses/', the course exploration page, if the course description is too long, then the class card on the right will overflow off the card. Ex: CS1660, CS1675.

If you add 'overflow: auto' to the css class 'text-xs', this seems to fix the issue.

**Comment by owini** [comment]
@Steven-Jarmell awesome! Feel free to contribute to the Wiki and create a PR. Thanks!
